"""Standard quality-comparison prompts (Korean + English mix)."""

QUALITY_PROMPTS: list[dict] = [
    {"id": "ko_reason_01", "lang": "ko", "category": "reasoning",
     "prompt": "정수 a, b, c가 있을 때 a + b = 12, b + c = 17, a + c = 13이다. a, b, c의 값을 구해라."},
    {"id": "ko_reason_02", "lang": "ko", "category": "reasoning",
     "prompt": "철수는 영희보다 3살 많고, 영희는 민수보다 2살 어리다. 셋의 나이 합이 36일 때 각자의 나이를 구하라."},
    {"id": "ko_code_01", "lang": "ko", "category": "code",
     "prompt": "파이썬으로 주어진 문자열에서 가장 자주 나오는 단어 3개를 빈도순으로 반환하는 함수를 작성해라."},
    {"id": "ko_code_02", "lang": "ko", "category": "code",
     "prompt": "Rust로 두 정렬된 벡터를 합쳐 정렬된 새 벡터를 만드는 함수의 시그니처와 본문을 작성해라."},
    {"id": "ko_summary_01", "lang": "ko", "category": "summary",
     "prompt": "Apple Silicon은 통합 메모리 구조를 채택해 CPU와 GPU가 동일한 메모리 풀을 공유한다. 이 점이 LLM 추론에 어떤 이점을 주는지 200자 이내로 설명하라."},
    {"id": "ko_creative_01", "lang": "ko", "category": "creative",
     "prompt": "겨울밤 도심을 산책하는 사람의 시점에서 짧은 산문 시를 한 편 써라. 6행 이내."},
    {"id": "ko_factual_01", "lang": "ko", "category": "factual",
     "prompt": "조선시대 영조와 정조 시대의 가장 중요한 학문적 흐름을 두 가지만 짧게 설명하라."},
    {"id": "ko_translate_01", "lang": "ko", "category": "translation",
     "prompt": "다음 문장을 한국어로 자연스럽게 번역하라: 'The unified memory architecture eliminates the need for explicit data transfer between CPU and GPU.'"},
    {"id": "en_reason_01", "lang": "en", "category": "reasoning",
     "prompt": "If 5 machines take 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets? Explain the reasoning."},
    {"id": "en_reason_02", "lang": "en", "category": "reasoning",
     "prompt": "A bag has 3 red, 5 blue, and 2 green marbles. You draw 2 without replacement. What is the probability both are blue?"},
    {"id": "en_code_01", "lang": "en", "category": "code",
     "prompt": "Write a Python function that returns the longest common subsequence of two strings using dynamic programming."},
    {"id": "en_code_02", "lang": "en", "category": "code",
     "prompt": "Show a minimal SQL query that finds the second-highest salary from an employees table without using LIMIT/TOP."},
    {"id": "en_summary_01", "lang": "en", "category": "summary",
     "prompt": "Summarize the difference between MoE (Mixture of Experts) and dense transformer architectures in three bullet points."},
    {"id": "en_creative_01", "lang": "en", "category": "creative",
     "prompt": "Write a six-line haiku-style poem about an SSD failing at 3 AM in a server rack."},
    {"id": "en_factual_01", "lang": "en", "category": "factual",
     "prompt": "Name three core differences between TCP and QUIC at the transport layer."},
    {"id": "en_translate_01", "lang": "en", "category": "translation",
     "prompt": "Translate to formal English: '오늘 회의는 인프라 비용 절감 방안에 집중합니다.'"},
    {"id": "ko_long_01", "lang": "ko", "category": "long_context",
     "prompt": "다음 요구사항으로 FastAPI 서버 한 파일을 작성해라: (1) /health GET 엔드포인트, (2) /sum POST가 정수 배열을 받아 합을 반환, (3) /sum은 1MB 이상의 페이로드를 거부, (4) 모든 응답에 X-Server-Ms 헤더 추가. 코드만 출력."},
    {"id": "en_long_01", "lang": "en", "category": "long_context",
     "prompt": "Design the schema for a multi-tenant note-taking app supporting nested folders, sharing, and full-text search. List the tables, key columns, and important indexes. Explain trade-offs in 5 sentences."},
    {"id": "ko_edge_01", "lang": "ko", "category": "edge",
     "prompt": "한국어로 '말'은 동음이의어다. 가능한 의미를 4가지 이상 들고 각 의미를 한 문장 예시로 보여라."},
    {"id": "en_edge_01", "lang": "en", "category": "edge",
     "prompt": "Explain why 0.1 + 0.2 != 0.3 in IEEE 754 floating point. Use one short example."},
]
